packages:
  - apps/*
  - packages/*

catalog:
  '@mysten/dapp-kit': ^0.19.11
  '@mysten/sui': ^1.45.2
  '@mysten/suins': ^0.9.12
  '@mysten/wallet-standard': ^0.19.9
  '@mysten/walrus': ^0.8.6
  '@tanstack/react-query': ^5.90.12
  '@types/debug': ^4.1.12
  '@types/node': ^22.19.1
  '@zenfs/archives': ^1.3.1
  '@zenfs/core': ^2.4.3
  '@zenfs/dom': ^1.2.5
  debug: ^4.4.3
  tsdown: ^0.17.3
  typescript: ^5.9.3
  wrangler: ^4.53.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - sharp
  - workerd
