packages:
  - apps/*
  - packages/*

catalog:
  '@mysten/dapp-kit': ^0.19.4
  '@mysten/sui': ^1.42.0
  '@mysten/suins': ^0.9.5
  '@mysten/wallet-standard': ^0.19.2
  '@mysten/walrus': ^0.7.5
  '@types/node': ^22.13.4
  typescript: ^5.9.2
  wrangler: '^4.43.0'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - lefthook
  - sharp
  - workerd

overrides:
  "@vanilla-extract/rollup-plugin": "npm:@toanzzz/vanilla-extract-rollup-plugin@1.4.2" # Temp fix while waiting for vanilla-extract to publish a 1.4.2 version